### PR TITLE
Fix detecting new password input in form

### LINKED ISSUE #2710: A form input element can be removed after it has been initially detected but before the observer has started
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

If the form input elements for a password and a username have already been detected and stored, but the observer hasn't started yet, then if any of them are removed and a new input is added, the change won't be detected and an invalid element will be stored

Image

I've actually run into this issue on a site that wraps an input element in a div by setting its `outerHTML`, similarly to the example provided below

### Expected Versus Actual Behavior

Expected: The extension is able to detect a new input element after the original one has been deleted
Actual: It can't because the observer hasn't started yet

### Steps to Reproduce

1. Host the [attached HTML](https://github.com/user-attachments/files/22574380/test.html)
2. Adjust the delay in the script if required
3. Try to fill in the password using KeePassXC-Browser

### KeePassXC-Browser Debug Information

```Text
KeePassXC - 2.7.10
KeePassXC-Browser - 1.9.9.6
Operating system: Win64
Browser: Chrome/Chromium 140.0.0.0
```

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX". )
Continues from https://github.com/keepassxreboot/keepassxc-browser/pull/2682. It's enough to replace the combination password field without adding it to the `passwordInputs` list.

* Fixes #2710

## Screenshots or videos
[NOTE]: # ( Use if available. )
[NOTE]: # ( Do not include screenshots of your actual database credentials! )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( Also describe how to test the changes manually. )
Tested this with the same sites in https://github.com/keepassxreboot/keepassxc-browser/pull/2682:
https://app.fastmail.com/
https://www.patreon.com/

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: keepassxc-browser/content/fields.js [hunk 1]
```diff
@@ -104,8 +104,8 @@ kpxcFields.getExistingCombination = function(combination) {
         existingCombination.password ??= combination.password;
         if (existingCombination.passwordInputs?.length === 0) {
             existingCombination.passwordInputs = combination.passwordInputs;
-        } else {
-            existingCombination.passwordInputs.push(combination.password);
+        } else if (combination?.password) {
+            existingCombination.password = combination.password;
```
Comment (droidmonkey) [inline keepassxc-browser/content/fields.js:109]: Add a comment here explaining that if we have a valid password field combination then force assign it to the existing combination field regardless if it was assigned previously or not.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

**Review by droidmonkey — APPROVED** [review]
