### PR TITLE
Fix filling wrapped input fields

### LINKED ISSUE #2684: reddit.com still struggles to work with 1.9.9.6
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

Site specific login issue: version 1.9.9.6 applied mitigations for login data not being filled on reddit website in https://github.com/keepassxreboot/keepassxc-browser/pull/2677

Test 1.9.9.6 w Firefox 1.4.4 nightly and found two issues:

1. keyboard shortcut on reddit.com login overlay is not filling the fields `Email or username` and `Password`, filling the fields now works as expected when selection a login from the dropdown, so in general the fix is confirmed
2. TOTP is neither fillied via keyboard shortcut nor right click contextual menu option, the KeePassXC login is not showing in that field

### Expected Versus Actual Behavior

Keyboard shortcut should be supported and TOTP information should be filled.

### Steps to Reproduce

See above

### KeePassXC-Browser Debug Information

```Text
N/A
```

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX". )
Some pages wrap the actual input field as a child element, and when using the fill from active element (context menu or keyboard shortcut), the fill is made to the wrapper element instead. Added a new method before the fill that can check the possible child elements from a custom `INPUT` element.

Also fixed an exception from `passwordInputs` in `form.js`. Reddit sometimes triggered this check because an iframe had two password fields.

* Fixes #2684

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( Also describe how to test the changes manually. )
Manually using Reddit's login page and 2FA field from context menu or keyboard shortcut. The actual input is not filled without the fix.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: keepassxc-browser/content/keepassxc-browser.js [hunk 1]
```diff
@@ -736,12 +736,20 @@ kpxc.setValue = function(field, value, forced = false) {
         field.checked = true;
     }
 
+    // Make sure the input is not wrapped inside another element (custom INPUT element)
+    if (field?.nodeName !== 'INPUT' && field?.nodeName?.includes('INPUT')) {
+        const childInput = field?.querySelector('input');
+        const fieldsFromShadowDOM = kpxcObserverHelper.findInputsFromShadowDOM(field);
+        field = childInput ?? fieldsFromShadowDOM[0];
```
Comment (droidmonkey) [inline keepassxc-browser/content/keepassxc-browser.js:743]: Need to check that fieldsFromShadowDOM is not empty

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: keepassxc-browser/content/keepassxc-browser.js (hunk 1 above)
Comment (varjolintu) [reply keepassxc-browser/content/keepassxc-browser.js:743]: This is actually ok because an element from empty array will be set to `undefined` if not found. The next function called will do the check, and I adjusted it a little bit.

**Review by droidmonkey — APPROVED** [review]
