### PR TITLE
Show Win64 platform correctly in About page.

### LINKED ISSUE #1155: Reports Win32 when on x86_64 on the about page of the Chrome browser extension
## Expected Behavior

Display the correct OS info on the extension page.

## Current Behavior

The settings page of the extension lists win32 as the OS when on x86_64

I don´t know how important this is but If anything relies on this info it will not act properly

## Steps to Reproduce (for bugs)

Go to settings on the browser extension page and click on the About page. It reports OS as win32 when on x86_64

1.
2.
3.
4.

## Debug info

About info provided by:

**EXTENSION**
KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Win32
Browser: Chrome/Chromium 87.0.4280.88

**APPLICATION**
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.6

**cheers!!!**

### PR DESCRIPTION
**Pull request by varjolintu**
Fixes #1155.

### CODE REVIEW

**Review by phoerious — APPROVED** [review]

File: keepassxc-browser/options/options.js [hunk 1]
```diff
@@ -562,9 +562,14 @@ options.initSitePreferences = function() {
 
 options.initAbout = function() {
     const version = browser.runtime.getManifest().version;
+    let platform = navigator.platform;
+    if (platform === 'Win32' && navigator.userAgent.includes('x64') || navigator.userAgent.includes('WOW64')) {
```
Comment (droidmonkey) [inline keepassxc-browser/options/options.js:566]: Recommend wrapping the or'd conditions:

```suggestion
    if (platform === 'Win32' && (navigator.userAgent.includes('x64') || navigator.userAgent.includes('WOW64'))) {
```

**Review by droidmonkey — APPROVED** [review]
