### PR TITLE
Prevent Illegal Invokcation on getPublicKey/getPublicKeyAlgorithm

### LINKED ISSUE #2322: Illegal Invocation error on getPublicKey and getPublicKeyAlgorithm calls
## Expected Behavior

Do not get Illegal Invocation error on calling **getPublicKey** and **getPublicKeyAlgorithm** methods or override them instead of inheriting from prototype 

## Current Behavior

If you trying to call **getPublicKey** or **getPublicKeyAlgorithm** methods from AuthenticatorAttestationResponse of KeepassXC app you will get Illegal invocation due to inheritance those functions via AuthenticatorAttestationResponse prototype

## Possible Solution

Fix createAttestationResponse in passkeys.js as:

```js
const createAttestationResponse = function(publicKey) {
    const response = {
        attestationObject: kpxcBase64ToArrayBuffer(publicKey.response.attestationObject),
        clientDataJSON: kpxcBase64ToArrayBuffer(publicKey.response.clientDataJSON),
        getAuthenticatorData: () => kpxcBase64ToArrayBuffer(publicKey.response?.authenticatorData),
        getTransports: () => [ 'internal' ]
    };

    // Prevent Illegal invocation error
    const responseWithProto = Object.setPrototypeOf(response, AuthenticatorAttestationResponse.prototype);
    responseWithProto.getPublicKey = undefined;
    responseWithProto.getPublicKeyAlgorithm = undefined;

    return responseWithProto;
};
```

this solution proposed via #2323 PR

## Steps to Reproduce (for bugs)

1. Initiate Registration ceremony 
2. Confirm new passkeys creation at KeepassXC interface
3. Try to call `publicKey.response.getPublicKey` or `publicKey.response.getPublicKeyAlgorithm` in userside JS code
4. get Illegal invocation Exception

## Debug info

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.2
Operating system: Linux
Browser: Chromium

### PR DESCRIPTION
**Pull request by Keroosha**
Fixes #2322

### CODE REVIEW

File: keepassxc-browser/content/passkeys.js [hunk 1]
```diff
@@ -34,7 +34,12 @@ const createAttestationResponse = function(publicKey) {
         getTransports: () => [ 'internal' ]
     };
 
-    return Object.setPrototypeOf(response, AuthenticatorAttestationResponse.prototype);
+    // Prevent Illegal invocation error
+    const responseWithProto = Object.setPrototypeOf(response, AuthenticatorAttestationResponse.prototype);
+    responseWithProto.getPublicKey = () => null;
```
Comment (varjolintu) [inline keepassxc-browser/content/passkeys.js:39]: Why not define these directly to the `response` above?

Comment (Keroosha) [reply keepassxc-browser/content/passkeys.js:39]: We can merge it

**Review by varjolintu — APPROVED** [review]
