### PR TITLE
Fix await with TOTP fill, code cleaning

### LINKED ISSUE #569: github totp hotkey not work
## github totp not work, but dropbox is normal.

image

### PR DESCRIPTION
**Pull request by varjolintu**
- Fix a missing `await`
- Fix errors with `define.js`
- General code cleaning

Fixes #569.

### CODE REVIEW

**Comment by varjolintu** [comment]
@droidmonkey I'll make a new release after this one is approved.

File: keepassxc-browser/content/define.js [hunk 1]
```diff
@@ -290,32 +286,20 @@ kpxcDefine.skip = function(e) {
     }
 };
 
-kpxcDefine.again = function(e) {
-    if (!e.isTrusted) {
```
Comment (droidmonkey) [inline keepassxc-browser/content/define.js]: Does removing these checks expose us to any security issues?

Comment (varjolintu) [reply keepassxc-browser/content/define.js]: No, because `isTrusted` is already handled in the main function `kpxcDefine.keyDown()`. This is why these are removed.

Comment (droidmonkey) [reply keepassxc-browser/content/define.js]: Perfect, this is ready then
