### PR TITLE
Ignore partial nodeNames

### LINKED ISSUE #2701: KeepassXC-Browser extension Slowing Down Firefox on Reddit.com
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

After an update to Firefox ESR 140.3 a slow down warning is shown under certain conditions, definitely on a reddit page with a lot of comments when opening the lightbox. It occurs under other circumstances, but the before is consistent.

Example of the warning:
Image

This behavior did not occur on Firefox ESR 128.14.

### Actual Behavior

The lightbox opens slowly and a slow down warning by Firefox is shown.

This works slowly on [a page with a lot of comments](https://www.reddit.com/r/TeenIndia/comments/1nohywg/what_is_this_called_in_your_language_guys/).

### Expected behavior

I do not expect to see a slow down warning from Firefox.

This works correctly on [this page](https://www.reddit.com/r/debian/comments/1no6sma/bye_bye_arch_hello_debian/).

### Steps to Reproduce

1. Browse to a page with a lot of comments, [for example](https://www.reddit.com/r/TeenIndia/comments/1nohywg/what_is_this_called_in_your_language_guys/)
2. Click on the image (it is of a person in a bikini)
3. Wait to for the lightbox with a larger image to open
4. as it opens the slowdown is shown
5. close the image using the `X` in the top right
6. See the slowdown occur again

### KeePassXC-Browser Debug Information

```Text
KeePassXC - 2.7.10
KeePassXC-Browser - 1.9.9.6
Operating system: Linux x86_64
Browser: Mozilla Firefox 140.0 w/ Betterfox
```

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX". )
Some dynamically created pages with a lot of comments passes the Mutation Observer's ignore list. The change introduces a list for partial NodeNames that should be ignored as well.

Partially fixes #2701

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( Also describe how to test the changes manually. )
Manually using reddit.com

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: keepassxc-browser/content/observer-helper.js [hunk 1]
```diff
@@ -312,6 +320,7 @@ kpxcObserverHelper.ignoredNode = function(target) {
     if (!target
         || kpxcObserverHelper.ignoredNodeTypes.some(e => e === target.nodeType)
         || kpxcObserverHelper.ignoredNodeNames.some(e => e === target.nodeName)
+        || kpxcObserverHelper.ignoredPartialNodeNames.some(e => target.nodeName?.includes(e))
         || target.nodeName.startsWith('YTMUSIC')
         || target.nodeName.startsWith('YT-')) {
```
Comment (droidmonkey) [inline keepassxc-browser/content/observer-helper.js:325]: Include these in the partial node name list? 

Also should it be startswith or contains for the partial node check?

Comment (varjolintu) [reply keepassxc-browser/content/observer-helper.js:325]: For now I'd like to keep those two checks separate: Nodes that starts with a certain string & nodes that includes a certain string (rest is generated).

Comment (droidmonkey) [reply keepassxc-browser/content/observer-helper.js:325]: Sounds good

**Review by droidmonkey — APPROVED** [review]
