### PR TITLE
Fill whole combination when Autocomplete Menu is disabled

### LINKED ISSUE #1973: Filling with Autocomplete Menu disabled does not fill the whole combination
## Expected Behavior
I expect to fill usernames and passwords.

## Current Behavior
Filling of logins is not working well since I upgraded recently.

1. It works from the toolbar button
2. If I use the keyboard shortcut or the right-click menu for "Fill username and password" then it fills the username into wherever my cursor is. If there are multiple logins it does not show a menu it just picks one.
3. If I do "Fill password only" then it puts the password into wherever my cursor is, even if that's the username field. Again it doesn't show a menu.

## Steps to Reproduce (for bugs)
As above. Here are some of my settings:

- OFF Activate username field icons.
- OFF Activate autocomplete for username fields
- ON Auto-submit login forms

## Debug info
KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.7
Operating system: Linux x86_64
Browser: Mozilla Firefox 117.0

### PR DESCRIPTION
**Pull request by varjolintu**
If Autocomplete Menu is disabled from the extension settings, only active element is filled with username or password, not the whole combination.

Note: Filling only the active element should be done only if a combination is not detected at all (for example single username field that is not automatically detected).

Fixes #1973.

### CODE REVIEW

File: keepassxc-browser/content/fill.js [hunk 1]
```diff
@@ -64,7 +64,7 @@ kpxcFill.fillFromCombination = async function(passOnly) {
     // Set focus to the input field
     field.focus();
 
-    if (kpxc.credentials.length > 1) {
+    if (kpxc.credentials.length > 1 && kpxc.settings.autoCompleteUsernames) {
         // More than one credential -> show autocomplete list
         kpxcUserAutocomplete.showList(field);
     } else {
```
Comment (droidmonkey) [inline keepassxc-browser/content/fill.js:70]: I feel like this changes the else condition. I am not familiar with the autoCompleteUsernames option

**Comment by droidmonkey** [comment]
I may be getting old but that code is so hard to read. The switching between combinations and credentials...

File: keepassxc-browser/content/fill.js (hunk 1 above)
Comment (varjolintu) [reply keepassxc-browser/content/fill.js:70]: The setting is named a bit poorly, but when it's `true` the Autocomplete Menu is shown when needed. Before this change the filling from combination was prevented if the option was disabled, but actually that needs to be checked later when we are actually trying to show the list.

If the option is disabled and no list is shown, the first credential will be filled.

Comment (droidmonkey) [reply keepassxc-browser/content/fill.js:70]: Would it be a big change to change the name of the setting to align with its use?

Comment (varjolintu) [reply keepassxc-browser/content/fill.js:70]: If we change the name, we need to make a function that detects the old setting and transfers the value to the new one. Otherwise old configs are gonna reset the option. So, it's possible.

Comment (droidmonkey) [reply keepassxc-browser/content/fill.js:70]: Save that for protocol v2

**Review by droidmonkey — APPROVED** [review]
