### PR TITLE
Fix Steam TOTP

### LINKED ISSUE #1710: Steam new TOTP
Similar to #1703 steam has a new interface for handling TOTPs. Keepassxc-browser currently does not identify the field as totp and one has to copy/paste to fill in. It would be nice if the extensions handle this field correctly. Thanks!

image

### PR DESCRIPTION
**Pull request by varjolintu**
Steam also uses a segmented 2FA, but with five alphanumerics instead of six numbers. Some hard-coded requirements for the six char length is changed to a more dynamic implementation when doing the fill.

Needs to be tested properly. Steam locked my account temporarily when making the fix..

Fixes #1710.

### CODE REVIEW

File: keepassxc-browser/content/fields.js [hunk 1]
```diff
@@ -92,9 +92,12 @@ kpxcFields.getSegmentedTOTPFields = function(inputs, combinations) {
...
         return;
     }
-    const addTotpFieldsToCombination = function(inputFields) {
+
+    let exceptionFound = false;
+
+    const addTotpFieldsToCombination = function(inputFields, ignoreLength = false) {
         const totpInputs = Array.from(inputFields).filter(e => e.nodeName === 'INPUT' && e.type !== 'password' && e.type !== 'hidden');
-        if (totpInputs.length === 6) {
+        if (totpInputs.length === 6 || ignoreLength) {
```
Comment (droidmonkey) [inline keepassxc-browser/content/fields.js:100]: How about instead we add a "expectedDigits" variable and default its value to 6.

**Review by droidmonkey — APPROVED** [review]

File: keepassxc-browser/content/fields.js (hunk 1 above)
Comment (varjolintu) [reply keepassxc-browser/content/fields.js:100]: Good idea.

Comment (droidmonkey) [reply keepassxc-browser/content/fields.js]: Ok not too concerned, you can merge
