### PR TITLE
Fix high CPU usage

### LINKED ISSUE #888: High CPU usage on Firefox with 1.6.x
Since the keepasxc-browser was upgraded to 1.6.0 (might be 1.6.1), in certain applications performance is really bad. Sometimes with 100% CPU usage on one core for multiple seconds and a really slow responding application. Sometimes leading to Firefox suggesting to temporarily disable the Keepassxc-browser add-on.
This CPU usage and slow response disappears when I disable the add-on.

Some alleviation of this issue has been reached in 1.6.3 (see issue #835), but the situation has not been fixed for all applications.
I experience the same issue on both Windows 10 and Fedora 31/32, which are different PC's that have a CPU capable enough and didn't present this issue < 1.6.0.

## Expected Behavior

I expect the keepassxc-browser add-on to have a minimal impact. As it has been < 1.6.0.

## Current Behavior

At the moment, in some apps, the performance impact gets so bad, I have to switch off the add-on to get back performance.

## Possible Solution

Observations:
1. This issue mainly seems to concentrate around applications that work with large numbers of dynamic rows/tables with data.
1. The CPU usage isn't attributed by Firefox to the keepassxc-browser add-on, but to the actual application tab. When disabling the add-on, though, response time and cpu usage are greatly reduced.
1. The issue increases in time: at the end of the working day, when firefox is open for longer, the issue is more present: the cpu spikes and the response delays are longer.

## Steps to Reproduce (for bugs)

I still have major issues when using PhpMyAdmin, and then especially when filtering the folder list when there are a lot of foldrs in a database, for example.
I also have major issues with the [Kopano Webapp](https://demo.kopano.com/webapp/index.php) when working with larger numbers of e-mails and calendar appointments.

## Debug info

KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.3
Operating system: Win & Linux
Browser: Firefox

### PR DESCRIPTION
**Pull request by varjolintu**
Fixes most of the high CPU usage with pages like music.youtube.com.

Changes made:
- Some special rules are added for the Youtube site
- Fixes an issue where elements in MutationObserver's `addedNodes` or `removedNodes` were using a `nodeType` which should've been ignored. The check for the target itself was clearly not enough.
- Any filling actions etc. to ignored site is forbidden via context menu or popup.
- Many checks have been altered in a way that the fastest checks are always done first.
- `IntersectionObserver` is no longer initialized automatically.
- `kpxc.passwordFilled()` is no longer requested multiple times.
- Any input field already holding some class starting with `kpxc` is ignored and not handled again.
- `kpxc.initCredentialFields()` is now divided with a new function `kpxc.handleCredentialFields()` which doesn't have any site specific checks that are unnecessary when e.g. adding dynamic input fields for checking.

With these changes the inspected elements decreased from 942 to 241 when loading https://music.youtube.com and scrolling the page to the bottom. With https://system.aliorbank.pl/sign-in the time used for scripting is 10x smaller.

Fixes #888.

### CODE REVIEW

File: keepassxc-browser/content/keepassxc-browser.js [hunk 1]
```diff
@@ -318,20 +319,21 @@ kpxcFields.isSearchField = function(target) {
 };
 
 kpxcFields.isVisible = function(field) {
-    // Check for parent opacity
-    if (kpxcFields.traverseParents(field, f => f.style.opacity === '0')) {
+    // Check element position and size
+    const rect = field.getBoundingClientRect();
```
Comment (droidmonkey) [inline keepassxc-browser/content/keepassxc-browser.js:323]: What about being beyond the extent of the page as well? x > page.width()

File: keepassxc-browser/content/keepassxc-browser.js [hunk 2]
```diff
@@ -745,15 +767,27 @@ kpxcObserverHelper.getId = function(target) {
```
Comment (droidmonkey) [inline keepassxc-browser/content/keepassxc-browser.js]: Shouldn't this be an ||?

File: keepassxc-browser/content/keepassxc-browser.js [hunk 3]
```diff
@@ -896,10 +930,7 @@ kpxc.initObserver = function() {
 
         for (const mut of mutations) {
             // Skip text nodes and base HTML element
-            if (mut.target.nodeType === Node.TEXT_NODE
-                || mut.target.nodeName === 'HTML'
-                || mut.target.nodeName === 'LINK'
-                || mut.target.nodeName === 'HEAD') {
+            if (kpxcObserverHelper.ignoredNode(mut.target)) {
                 continue;
             }
```
Comment (droidmonkey) [inline keepassxc-browser/content/keepassxc-browser.js:935]: Again should be ||

File: keepassxc-browser/content/keepassxc-browser.js [hunk 4]
```diff
@@ -318,20 +319,21 @@ kpxcFields.isSearchField = function(target) {
 };
 
 kpxcFields.isVisible = function(field) {
-    // Check for parent opacity
-    if (kpxcFields.traverseParents(field, f => f.style.opacity === '0')) {
+    // Check element position and size
+    const rect = field.getBoundingClientRect();
+    if (rect.x < 0 || rect.y < 0 || rect.width < 8 || rect.height < 8) {
         return false;
```
Comment (droidmonkey) [inline keepassxc-browser/content/keepassxc-browser.js:325]: What about elements that are beyond the page extents?

File: keepassxc-browser/content/keepassxc-browser.js [hunk 5]
```diff
@@ -745,15 +767,27 @@ kpxcObserverHelper.getId = function(target) {
     return `kpxc${target.clientTop}${target.clientLeft}${target.clientWidth}${target.clientHeight}`;
 };
 
+kpxcObserverHelper.hasKpxcClass = function(target) {
+    if (!target.className
+        && !target.className.includes('kpxc')) {
```
Comment (droidmonkey) [inline keepassxc-browser/content/keepassxc-browser.js:772]: This should be an ||

File: keepassxc-browser/content/keepassxc-browser.js [hunk 6]
```diff
@@ -1026,7 +1057,8 @@ kpxc.initCredentialFields = async function(forceCall, inputs) {
 
     _called.clearLogins = true;
 
-    if (kpxc.siteIgnored()) {
+    // No need to check this for every dynamically added inputs
+    if (inputs === undefined && kpxc.siteIgnored()) {
```
Comment (droidmonkey) [inline keepassxc-browser/content/keepassxc-browser.js:1061]: Again should be ||

File: keepassxc-browser/content/keepassxc-browser.js (hunk 5 above)
Comment (varjolintu) [reply keepassxc-browser/content/keepassxc-browser.js:772]: Oops.

File: keepassxc-browser/content/keepassxc-browser.js (hunk 6 above)
Comment (varjolintu) [reply keepassxc-browser/content/keepassxc-browser.js:1061]: The whole point of this check is to use `kpxc.siteIgnored()` only when `kpxc.initCredentialFields()` is called without dynamically added input fields. But now when I think of it, the whole site ignored check should be done outside of this function when the page loads, not with every possible check. So making a fix.

Comment (droidmonkey) [reply keepassxc-browser/content/keepassxc-browser.js:1061]: Good point! Even better

**Comment by varjolintu** [comment]
@droidmonkey All the changes made. I also listed them all in the PR description.

File: keepassxc-browser/content/keepassxc-browser.js [hunk 7]
```diff
@@ -1013,7 +1054,8 @@ kpxc.siteIgnored = function(condition) {
     return false;
 };
 
-kpxc.initCredentialFields = async function(forceCall, inputs) {
+// Initializes all input fields from the whole page
+kpxc.initCredentialFields = async function(forceCall) {
```
Comment (droidmonkey) [inline keepassxc-browser/content/keepassxc-browser.js:1058]: This function signature changed but don't see where any calls to it changed or where inputs was dropped from use.

Comment (varjolintu) [reply keepassxc-browser/content/keepassxc-browser.js:1058]: See line 827 inside `kpxcObserverHelper.handleObserverAdd()`. The whole `inputs` parameter was added to `kpxc.initCredentialFields()` because of the input fields added by the observer.
