### PR TITLE
Requery form if password input has changed

### LINKED ISSUE #2737: Password field detection broken by Moodle
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

Both Moodle instances of the two unis I have had an account with, and the moodle sandbox instance have broken password field detection. Initially the password field served by the web server is correctly detected, but then after a short delay _for some reason_ Moodle swaps out the password field with a different DOM object that looks exactly the same, but is no longer the instance that KeePassXC picked up (hovering over the element in the debug logs in the JS console does not highlight the current password input element at that point).
The username field is correctly detected and stays around / keeps working.

Right click -> "Fill Password Only" does not work.

"Redetect login fields" correctly detects the new password input field after this, but that button is not offered for me on the sites I actually have credentials for (I get the "Select the login information you would like to get entered into the page." picker instead).

<details>
<summary>Debug output in JS Console (click to expand)</summary>

Before "Redetect login fields":
```
[Debug keepassxc-browser.js:229] KeePassXC-Browser - Input fields found: global.js:172:13
Array [ input#username.form-control.form-control-lg, input#password.form-control.form-control-lg ]
global.js:175:17
[Debug ] KeePassXC-Browser - Login field combinations identified: global.js:172:13
Array [ {…} ]
global.js:175:17
[Debug fields.js:227] KeePassXC-Browser - Input fields found: global.js:172:13
Array [ input#username.form-control.form-control-lg, input#password.form-control.form-control-lg ]
global.js:175:17
[Debug ] KeePassXC-Browser - Login field combinations identified: global.js:172:13
Array [ {…} ]
global.js:175:17
Starting Moodle session timeout warning. first.js:1262:3375
[Debug observer-helper.js:252] KeePassXC-Browser - Input fields found: global.js:172:13
Array [ input#password.form-control.form-control-lg ]
global.js:175:17
[Debug observer-helper.js:278] KeePassXC-Browser - Input fields found: global.js:172:13
Array [ input#password.form-control.form-control-lg ]
global.js:175:17
[Debug jquery-3.7.1.min.js:2] KeePassXC-Browser - Login field combinations identified: global.js:172:13
Array [ {…} ]
global.js:175:17
[Debug observer-helper.js:266] KeePassXC-Browser - Error: No combination found. global.js:172:13
```

After "Redetect login fields":
```
[Debug keepassxc-browser.js:229] KeePassXC-Browser - Input fields found: global.js:172:13
Array [ input#username.form-control.form-control-lg, input#password.form-control.form-control-lg ]
global.js:175:17
[Debug ] KeePassXC-Browser - Login field combinations identified: global.js:172:13
Array [ {…} ]
global.js:175:17
[Debug fields.js:227] KeePassXC-Browser - Input fields found: global.js:172:13
Array [ input#username.form-control.form-control-lg, input#password.form-control.form-control-lg ]
global.js:175:17
[Debug ] KeePassXC-Browser - Login field combinations identified: global.js:172:13
Array [ {…} ]
global.js:175:17
```

</details>

### Expected Versus Actual Behavior

**Expected:**
When clicking the KeePassXC icon in the username field on a Moodle instance, both username *and* password are correctly filled in.

**Actual:**
Only the username is filled in, and the password field also cannot be filled with "Fill Password Only".

### Steps to Reproduce

1. Open Moodle instance login page (https://sandbox.moodledemo.net/login/index.php)
2. Click KeePassXC icon in username field
3. Only the username is filled in
  a. "Fill Password Only" on the password field does nothing

### KeePassXC-Browser Debug Information

```Text
KeePassXC - 2.7.10
KeePassXC-Browser - 1.9.10
Operating system: Linux x86_64
Browser: Mozilla Firefox 146.0
```

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX". )
If login form has a password input field that has been replaced by the page script with an identical input element, the extension still tries to fill the old one and fails.
If the password input in the combination differs from the form saved in the combination, query the form again and identify the identical field. If found, replace the combination's password input with the new one.

A rare case (and a bit hacky), but it might fix some other sites as well.

* Fixes #2737

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( Also describe how to test the changes manually. )
Test with page: https://sandbox.moodledemo.net/login/index.php

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: keepassxc-browser/content/fill.js [hunk 1]
```diff
@@ -427,3 +439,26 @@ const showErrorNotification = async function(errorMessage, notificationType = 'e
...
 };
+
+// Checks if two NamedNodeMaps (attribute lists) are equal
+const areNamedNodeMapsEqual = function(currentNodeMap, newNodeMap) {
+    if (!currentNodeMap || !newNodeMap) {
+        return false;
+    }
+
+    const passwordFieldAttributes = Array.from(currentNodeMap);
+    const newPasswordFieldAttributes = Array.from(newNodeMap);
```
Comment (droidmonkey) [inline keepassxc-browser/content/fill.js]: Since this is a generic function, don't use password in the variable names

File: keepassxc-browser/content/fill.js [hunk 2]
```diff
@@ -245,6 +245,18 @@ kpxcFill.fillInCredentials = async function(combination, predefinedUsername, uui
...
     }
 
+    // Update the password field if form has been updated with a new identical element (Moodle).
+    // If found, replace the new input field to the combination.
+    if (combination?.form && combination?.password && !combination.form.contains(combination.password)) {
+        const formInputs = kpxcObserverHelper.getInputs(combination.form);
+        const newPasswordField = formInputs?.find((formInput) =>
+            formInput?.getLowerCaseAttribute('type') === 'password');
+        if (newPasswordField && areNamedNodeMapsEqual(combination.password.attributes, newPasswordField.attributes)
+        ) {
```
Comment (droidmonkey) [inline keepassxc-browser/content/fill.js]: Awkward line overhang

**Review by droidmonkey — CHANGES_REQUESTED** [review]

**Review by droidmonkey — APPROVED** [review]

**Comment by rosa2** [comment]
Hi,

I have Keepassxc-browser version 1.9.11
I keep having the problem with password not written in its field in Moodle log in.
Browser: LibreWolf 146.0-2
In the javascript console I don't get errors.

Have a good holidays, thanks for the software and if you consider, I can open a new issue.

**Comment by varjolintu** [comment]
> Hi,
> 
> I have Keepassxc-browser version 1.9.11 I keep having the problem with password not written in its field in Moodle log in. Browser: LibreWolf 146.0-2 In the javascript console I don't get errors.
> 
> Have a good holidays, thanks for the software and if you consider, I can open a new issue.

You can reproduce this with the same page described in the issue's first message? https://sandbox.moodledemo.net/login/index.php

**Comment by jedenastka** [comment]
> You can reproduce this with the same page described in the issue's first message? https://sandbox.moodledemo.net/login/index.php

I don't know if they can, but I can.

Update: actually, it seems only picking a login from the list is broken - clicking on the autofill icon works. I'll raise an issue for that later if I have some time.
