### PR TITLE
Use defaultView instead of scrollingElement when positioning icons and menus

### LINKED ISSUE #1872: Autocomplete positioning issue when document is in quirks mode
## Expected Behavior

The autocomplete dropdown should be properly positioned when a page is in quirks mode.

## Current Behavior

I noticed that on https://identity.pagerduty.com/, the autocomplete dropdown is not positioned properly. Turns out that the page is rendered in quirks mode and `document.scrollingElement` is `null`. (see below for javascript error)

Screenshot 2023-03-03 at 17 22 55

## Possible Solution

I tried this:

```javascript
const scrollingElement = document.scrollingElement || document.documentElement;

// replace references to document.scrollingElement with just "scrollingElement"
```

This works fine until you scroll the document. When the document is scrolled the dropdown is not following along. If this had fully solved the problem then I would have opened a PR.

## Steps to Reproduce (for bugs)

1. Create an entry for https://identity.pagerduty.com/.
2. Go to https://identity.pagerduty.com/.
3. Click the username input field.
4. Open javascript console and see `scrollingElement` error (screenshot below).

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.5.1
Operating system: Mac
Browser: Chrome

Screenshot 2023-03-03 at 17 22 14

An errant `<meta>` tag is causing the page to render in quirks mode:

Screenshot 2023-03-03 at 17 27 17

```
document.compatMode
'BackCompat'
```

### PR DESCRIPTION
**Pull request by varjolintu**
With some webpages `document.scrollingElement` or `document.documentElement` are not providing correct `scrollTop` and `scrollLeft` values. Instead `document.defaultView` is used with `scrollX` and `scrollY` values.

Needs a little more testing to ensure this doesn't break any sites with scrolling.

Fixes #1872.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Nothing like consistency in web development! This is why I quit making web pages back in 2010.

File: keepassxc-browser/content/ui.js [hunk 1]
```diff
@@ -143,8 +143,8 @@ kpxcUI.setIconPosition = function(icon, field, rtl = false, segmented = false) {
         top = iconOffset[1];
     }
 
-    const scrollTop = document.scrollingElement ? document.scrollingElement.scrollTop : 0;
-    const scrollLeft = document.scrollingElement ? document.scrollingElement.scrollLeft : 0;
+    const scrollTop = document.defaultView ? document.defaultView.scrollY : document.scrollingElement.scrollTop;
+    const scrollLeft = document.defaultView ? document.defaultView.scrollX : document.scrollingElement.scrollLeft;
```
Comment (stefansundin) [inline keepassxc-browser/content/ui.js:147]: Could also do something like this:

```suggestion
    const scrollLeft = document.defaultView?.scrollX ?? document.scrollingElement?.scrollLeft ?? 0;
```

Comment (varjolintu) [reply keepassxc-browser/content/ui.js:147]: Gotta bump up the minimum Firefox version for these (67 -> 74 so no biggie). But those are a nice cleanup.

Comment (stefansundin) [reply keepassxc-browser/content/ui.js]: I think both `?.` and `??` are in use in small parts of the code already. I think I added the `?.` before I even considered compatibility.

Comment (varjolintu) [reply keepassxc-browser/content/ui.js]: If you already use browser greater than the minimum version there's no problems. But if you use e.g. Firefox 67 I bet those will not work and will throw an exception. A rare situation of course, because I doubt no one is using versions that old.

**Review by droidmonkey — APPROVED** [review]
