### PR TITLE
Check document.dir to determine the position of the icon.

### LINKED ISSUE #701: Position of textfield icon in RTL Websites
The position of the "green key" icon in RTL(right to left) websites is rendered on top of the text instead of the opposite site(left in this case).

## Expected Behavior
In RTL websites, the keepass icon should be displayed on the left side of the text field instead of right.

## Current Behavior
Currently, it's displayed on the right side and RTL text comes right below it. Making the first few letters unreadable.

## Possible Solution
Update the positioning of the icon to change depending on the `dir` value of the `<html>` tag.

## Steps to Reproduce
1. Open a login page in any RTL website.
2. The Keepass icon will be displayed on the right edge of the textfield: image

## Context
The plugin works nicely but the icon displayed over the text in RTL websites makes the first few letters unreadable.

## Debug Info
KeePassXC-Browser Version: 1.5.3
KeePassXC Version: 2.5.1
Operating system: Linux
Browser: Brave

### PR DESCRIPTION
**Pull request by layalk**
Function `kpxcUI.setIconPosition` doesn't take into consideration the direction of the page's direction. In RTL(right to left) websites, the icon is displayed on top of the text instead of the opposite side(left).
Fixes #701 .

### CODE REVIEW

File: keepassxc-browser/content/ui.js [hunk 1]
```diff
@@ -85,7 +85,12 @@ kpxcUI.setIconPosition = function(icon, field) {
     const size = Number(icon.getAttribute('size'));
 
     icon.style.top = Pixels((rect.top + document.scrollingElement.scrollTop) + offset + 1);
-    icon.style.left = Pixels((rect.left + document.scrollingElement.scrollLeft) + field.offsetWidth - size - offset);
+    if (document.dir == 'rtl') {
```
Comment (varjolintu) [inline keepassxc-browser/content/ui.js]: FYI: proper strict JavaScript comparison is `=== `.

Comment (layalk) [reply keepassxc-browser/content/ui.js]: You're right! I updated it. Thanks for the prompt feedback.

File: keepassxc-browser/content/ui.js [hunk 2]
```diff
@@ -85,7 +85,12 @@ kpxcUI.setIconPosition = function(icon, field) {
     const size = Number(icon.getAttribute('size'));
 
     icon.style.top = Pixels((rect.top + document.scrollingElement.scrollTop) + offset + 1);
-    icon.style.left = Pixels((rect.left + document.scrollingElement.scrollLeft) + field.offsetWidth - size - offset);
+    if (document.dir === 'rtl') {
+        icon.style.left = Pixels((rect.left + document.scrollingElement.scrollLeft) + offset);
+    }
```
Comment (droidmonkey) [inline keepassxc-browser/content/ui.js]: Put else on same line as close brace above

File: keepassxc-browser/content/ui.js [hunk 3]
```diff
@@ -85,7 +85,12 @@ kpxcUI.setIconPosition = function(icon, field) {
...
+    else {
```
Comment (droidmonkey) [inline keepassxc-browser/content/ui.js]: Put else on same line as closing brace above

Comment (layalk) [reply keepassxc-browser/content/ui.js]: Done.
