### PR TITLE
Fix filling TOTP with multiple pages

### LINKED ISSUE #161: "Fill TOTP" does nothing on Firefox 61b
Since the latest release of the extension (as of May 2018) I think there's a regression on the Fill OTP on Firefox, the code is not generated. At this time only noticed when logging on Github.
It works on Chromium and it worked on Firefox.

## Expected Behavior
The OTP generation should generate a token like it did before

## Current Behavior
During the OTP auth pahse, the OTP generation fails and the keepassxc icon shows a (non-selectable) confirmation of the credentials (see attached image)

## Steps to Reproduce (for bugs)
- Sign in on gihub
- keepassxc correctly autofills user+pass
- next step ORP, keepassxc does not produce the TOTP. Shows a  a (non-selectable) confirmation of the credentials.

## Debug info
KeePassXC-Browser Version: 1.1.3
KeePassXC Version: 2.3.3 
Operating system: Ubuntu 18.04, x86_64
Browser: Firefox only, Chromium is ok
Proxy used: YES

### PR DESCRIPTION
**Pull request by varjolintu**
If login screen has a separate page for TOTP filling the value will be preserved outside of content script.

Fixes #161.

### CODE REVIEW

File: keepassxc-browser/keepassxc-browser.js [hunk 1]
```diff
@@ -1515,23 +1518,26 @@ cip.fillInFromActiveElementTOTPOnly = function(suppressWarnings) {
...
-                const val = s["KPH: {TOTP}"];
-                if (val) {
-                    cip.setValue($sf, val);
+
+    browser.runtime.sendMessage({
+        action: 'page_get_login_id'
+    }).then((pos) => {
+        if (pos >= 0 && cip.credentials[pos]) {
+            // Check the value from stringFields (to be removed)
+            const $sf = _fs(fieldId);
```
Comment (phoerious) [inline keepassxc-browser/keepassxc-browser.js]: Why the $?  _sf() is also not very readable.

Comment (varjolintu) [reply keepassxc-browser/keepassxc-browser.js]: It's a common practice to use `$` when a variable is something jQuery uses directly. I've already removed these in the WIP No jQuery PR. I'll change this to a more readable form.
