### PR TITLE
Fix topmost input element check with labels

### LINKED ISSUE #2664: 1.9.9.3 Fails on bank web site
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

The firefox plugin 1.9.9.3 fails (icon not on username and no autofill) on the Wells Fargo web site.  1.9.9.4 fails as well.  Dropping back to 1.9.9.2 and it work.
https://www.wellsfargo.com/?fullsite=mba

### Expected Versus Actual Behavior

_No response_

### Steps to Reproduce

https://www.wellsfargo.com/?fullsite=mba

### KeePassXC-Browser Debug Information

Xubuntu 24.03.3, FIREFOX 128.14.0 esr

```--------------------------------
Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead. [home:337:3](https://news.google.com/home?hl=en-US&gl=US&ceid=US:en)
MouseEvent.mozInputSource is deprecated. Use PointerEvent.pointerType instead. [home:337:3](https://news.google.com/home?hl=en-US&gl=US&ceid=US:en)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Some cookies are misusing the recommended “SameSite“ attribute 94
[Error ] KeePassXC-Browser - page.initSettings: Error: Managed storage manifest not found [global.js:168:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Use of the orientation sensor is deprecated. [N1AB:1:222878](https://www.wellsfargo.com/rdXdvh/7qU/OSH/XI0U2tzC/V5kuGpzrJ2f2rt/ATs5MA/FhlAMHko/N1AB)
Use of the motion sensor is deprecated. [N1AB:1:223056](https://www.wellsfargo.com/rdXdvh/7qU/OSH/XI0U2tzC/V5kuGpzrJ2f2rt/ATs5MA/FhlAMHko/N1AB)
[Error ] KeePassXC-Browser - page.initSettings: Error: Managed storage manifest not found [global.js:168:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug keepassxc-browser.js:227] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug fields.js:206] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:271] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Error ] KeePassXC-Browser - page.initSettings: Error: Managed storage manifest not found [global.js:168:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. [8556c7b1.js:1:342283](https://connect.secure.wellsfargo.com/auth/static/depm/8556c7b1.js)
[Error ] KeePassXC-Browser - page.initSettings: Error: Managed storage manifest not found [global.js:168:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
InstallTrigger is deprecated and will be removed in the future. [8556c7b1.js:1:281894](https://connect.secure.wellsfargo.com/auth/static/depm/8556c7b1.js)
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. [api.js:17:50941](https://okra.wf.com/v2/9B8ED233-984B-4DE5-A7B6-3A370D9FF48B/api.js)
Error: 
[api.js:17:74075](https://okra.wf.com/v2/9B8ED233-984B-4DE5-A7B6-3A370D9FF48B/api.js)
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. [N1AB:1:138405](https://www.wellsfargo.com/rdXdvh/7qU/OSH/XI0U2tzC/V5kuGpzrJ2f2rt/ATs5MA/FhlAMHko/N1AB)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug observer-helper.js:245] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array []
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. [api.js:17:50941](https://okra.wf.com/v2/9B8ED233-984B-4DE5-A7B6-3A370D9FF48B/api.js)
Error: 
[api.js:17:74075](https://okra.wf.com/v2/9B8ED233-984B-4DE5-A7B6-3A370D9FF48B/api.js)
[Debug keepassxc-browser.js:227] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array [ input#userid.form-element.formElementText.login_field.signon-in.activeField
 ]
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
[Debug fields.js:206] KeePassXC-Browser - Input fields found: [global.js:160:13](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
Array [ input#userid.form-element.formElementText.login_field.signon-in.activeField
 ]
[global.js:163:17](moz-extension://a395e7bd-61b6-4ef0-9799-b4961d0aeb8c/common/global.js)
userData dropped because it was not a string, field name wfacookie [adrum-ext.b4436be974de477658d4a93afb752165.js:30:249](https://static.wellsfargo.com/assets/js/wfui/appdynamics/adrum-ext.b4436be974de477658d4a93afb752165.js)

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX". )
At some pages the input element has a `<label>` that is returned as the topmost element. Inputs have a separate property `.labels` ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/labels)) that can be used to check if the label element is actually related to the input we are checking.

A few pages might use a non-standard label, e.g. `<span>` element, but those cannot be checked reliably, and are ignored.

Fixes #2664

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( Also describe how to test the changes manually. )
Manually using the URLs in the issue thread.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: keepassxc-browser/content/fields.js [hunk 1]
```diff
@@ -416,13 +416,19 @@ kpxcFields.isTopElement = function(elem, rect) {
         return false;
     }
 
-    // Check topmost element from three points inside the input
-    const verticalMiddle = rect.top + (rect.height / 2);
     const rootNode = elem.getRootNode() ?? document;
+
+    // Returns the topmost element from point x,y. If the input has a label as the top element, allow it.
+    const getTopmostElement = (x) => {
+        const topElement = rootNode.elementFromPoint(x, rect.top + (rect.height / 2));
```
Comment (droidmonkey) [inline keepassxc-browser/content/fields.js]: Rect isnt captured by this inner function, is it implied that the parent scope rect is accessible here?

Comment (varjolintu) [reply keepassxc-browser/content/fields.js]: Yes. I can add the variable to the function for better readability. I should probably also check (just to be sure) that the label element is smaller than the input size.

**Review by droidmonkey — APPROVED** [review]
