### PR TITLE
Fix isFirefox() check

### LINKED ISSUE #2672: KeePassXC-Browser stops working on Firefox after changing User Agent to Chrome
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

If the User Agent is set to Chrome  in Firefox(by setting general.useragent.override in about:config to "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36" and restarting) the extension gets stuck at "Checking status".

I think this may have something to do with the changes made in this commit:https://github.com/keepassxreboot/keepassxc-browser/pull/2510/files#diff-d916a0d73ed1fe3f8df914320b309db296f0f9f6d651e8be56922591aab07250R79
because the extension used to work with overridden User Agent earlier this year.

Image

### Expected Versus Actual Behavior

Expected behavior: KeePassXC-Browser connects to the database if User Agent is overridden.

Actual behavior: KeePassXC-Browser  gets stuck at "Checking status". 

### Steps to Reproduce

1. Set "general.useragent.override" in about:config to "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36"
2. Restart Firefox
3. Try to connect to the database

### KeePassXC-Browser Debug Information

```Text
KeePassXC - 2.7.10
KeePassXC-Browser - 1.9.9.3
Operating system: Linux x86_64
Browser: Mozilla Firefox 142.0
```

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX". )
Fixes `isFirefox()` by setting the variable during extension start. Content scripts only request the already parsed value. Additional check for `browser.runtime.getBrowserInfo()` is added to the check, because this API call only exists in Firefox and currently it's the only way to distinquish Firefox if user has changed the browser user agent to something else.

Also moved few log messages to `console.debug()` instead, and changed `debugLogMessage()` to pass calls to that function. Especially the `page.js` spammed a lot of console messages because of the managed settings check.

* Fixes #2672

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( Also describe how to test the changes manually. )
Manually.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: keepassxc-browser/background/init.js [hunk 1]
```diff
@@ -161,13 +155,17 @@ const initListeners = async function() {
 };
 
 const initContextMenuItems = async function() { 
+    if (page.isFirefox) {
+        page.menuContexts.push('password');
```
Comment (droidmonkey) [inline keepassxc-browser/background/init.js:160]: As unlikely as it is to call this function multiple times, you should "reset" the menuContexts first in this function. Moving the initial entry of "editable" into here would be prudent.

File: keepassxc-browser/options/options.js [hunk 2]
```diff
@@ -982,6 +983,8 @@ window.addEventListener('scroll', function() {
 
         const keyRing = await browser.runtime.sendMessage({ action: 'load_keyring' });
         options.keyRing = keyRing;
+        options.isFirefox = await browser.runtime.sendMessage({ action: 'is_firefox' });
```
Comment (droidmonkey) [inline keepassxc-browser/options/options.js:986]: Shouldn't this be sussed out BEFORE calling the addEventListeners for click and scroll?

File: keepassxc-browser/popups/popup_functions.js [hunk 3]
```diff
@@ -16,7 +16,8 @@ async function initSettings() {
     });
 
     const customLoginFieldsButton = document.body.querySelector('#settings #choose-custom-login-fields-button');
-    if (isFirefox()) {
+    const isFirefox = browser.runtime.sendMessage({ action: 'is_firefox' });
+    if (isFirefox) {
```
Comment (droidmonkey) [inline keepassxc-browser/popups/popup_functions.js:20]: same here

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: keepassxc-browser/options/options.js (hunk 2 above)
Comment (varjolintu) [reply keepassxc-browser/options/options.js:986]: What click and scroll events do you mean here (and below)?

Comment (droidmonkey) [reply keepassxc-browser/options/options.js:986]: sorry this was a PR review failure, it was reporting this was in the add listener call... didn't look above this code block.

**Review by droidmonkey — APPROVED** [review]
