### PR TITLE
Fix/epicgames and paypal password inputs

### LINKED ISSUE #2798: broken site: paypal.com
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

PayPal has a bit of a weird login flow, and the extension doesn't handle it very well.
For context: I have two accounts saved for the site.

At first, only an email field is shown. The extension autofills this just fine.
After entering the email, a password field is shown instead. The extension does not detect this field at all, and instead the following happens:
- triggering autofill by keyboard shortcut opens the account selection popup in the top-left corner of the screen. 
  Selecting any account there does not visibly do anything.
- filling the password field by right-click -> fill password only does fill the field, but in my case with the wrong password (without prompting which account to use).
  I believe this already tracked by #2043, so I'll ignore it in this issue report.

### Expected Versus Actual Behavior

Expected: the password field should be detected correctly
Observed: it wasn't

### Steps to Reproduce

1. visit paypal.com
2. click login
3. enter e-mail
4. observe: password field is not auto-fillable

### KeePassXC-Browser Debug Information

```Text
KeePassXC - 2.7.11
KeePassXC-Browser - 1.9.11
Operating system: Linux x86_64
Browser: Mozilla Firefox 145.0
```

### LINKED ISSUE #2813: Password field not detected on epicgames.com
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

Provide the following info when making a report:
1. Exact login URL and the URL of your entry or entries: 
     login URL https://www.epicgames.com/id/login, entry URL epicgames.com
3. Dump of console output from the page (Firefox: Tools -> Browser Tools -> Web Developer Tools / Chromium-based: Tools -> Developer -> Javascript Console). Do this only if there's KeePassXC-Browser related output.
    N/A
5. Have you tried Username-Only Detection, choosing Custom Fields etc.
    yes
7. Are you using Autofill instead of the manual one.    
    manual
9. Check that you haven't denied the entry access. Edit entry -> Properties -> Plugin Data should show Allow/Deny settings.
    Have not denied access
11. Does it affect the Username Icon, Autocomplete Menu, Popup Menu?
    Everything works for the email box (username) but not the password box
13. Version 1.8.0 and later, enable Debug Logging from the settings and inspect the pages's JavaScript console. It should show all input fields detected.    Please note that sites that require credentials to be made are with lower priority.
```
global.js:176:17
[Debug keepassxc-browser.js:230] KeePassXC-Browser - Input fields found: global.js:173:13
Array [ input#email.MuiInputBase-input.MuiOutlinedInput-input.mui-10xq60c ]
global.js:176:17
[Debug ] KeePassXC-Browser - Login field combinations identified: global.js:173:13
Array [ {…} ]
global.js:176:17
[Debug fields.js:227] KeePassXC-Browser - Input fields found: global.js:173:13
Array [ input#email.MuiInputBase-input.MuiOutlinedInput-input.mui-10xq60c ]
global.js:176:17
[Debug ] KeePassXC-Browser - Login field combinations identified: global.js:173:13
Array [ {…} ]
global.js:176:17
[Debug observer-helper.js:278] KeePassXC-Browser - Input fields found: global.js:173:13
Array [ input#password.MuiInputBase-input.MuiOutlinedInput-input.mui-10xq60c ]
global.js:176:17
[Debug observer-helper.js:252] KeePassXC-Browser - Input fields found: global.js:173:13
Array []
global.js:176:17
[Debug observer-helper.js:252] KeePassXC-Browser - Input fields found: global.js:173:13
Array []
global.js:176:17
[Debug form.js:38] KeePassXC-Browser - Error: Empty password. global.js:173:13
[Debug keepassxc-browser.js:884] KeePassXC-Browser - Error: Empty password. global.js:173:13
[Debug keepassxc-browser.js:884] KeePassXC-Browser - Error: Empty password. global.js:173:13
undefined hsw.js line 2 > eval line 1 > eval:1:1274
```

### Expected Versus Actual Behavior

Expected: Autofill to work for both the email and password fields.
Actual: Autofill works for email. The green keepass icon does not show up for the password nor does popup menu show up.

Autofilling the email works but does not for the password field. I'm guessing because you have to type in the email first before the password box shows up.

### Steps to Reproduce

To log into Epic https://www.epicgames.com:
1. Click Sign In
3. Sign in with an email using autofill (sometimes you have to refresh to get the keepass popup to show up)
4. Click Continue, it will then show the password box
5. Type in password since the keepass popup doesn't show up
6. Click Sign In

### KeePassXC-Browser Debug Information

```Text
KeePassXC - 2.7.11
KeePassXC-Browser - 1.9.11
Operating system: Linux x86_64
Browser: Mozilla Firefox 146.0
```

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX". )
Fixed password input detection on Epic Games and PayPal. Also noticed that a recent change https://github.com/keepassxreboot/keepassxc-browser/pull/2745 broke the Reddit login form, so removed one line from the ignored nodenames list.

Added a few seprate comments  to the code why I did certain changes.

* Fixes #2798
* Fixes #2813

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( Also describe how to test the changes manually. )
Manually.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: keepassxc-browser/common/sites.js [hunk 1]
```diff
@@ -71,7 +71,7 @@ kpxcSites.detectUsernameFromPage = function() {
  * @returns {boolean}           True if an Element has a match with the identifier and document location
  */
 kpxcSites.exceptionFound = function(identifier, field) {
-    if (!identifier || identifier.length === 0) {
+    if ((!identifier || identifier.length === 0) && !field) {
```
Comment (varjolintu) [inline keepassxc-browser/common/sites.js:74]: We also call this function without any identified. It should return only if no parameters are set, or it's called only with an empty identifier without any element reference.

File: keepassxc-browser/common/sites.js [hunk 2]
```diff
@@ -108,6 +108,33 @@ kpxcSites.exceptionFound = function(identifier, field) {
...
+
+// Handles exceptions when returning or modifying existing combinations
+kpxcSites.combinationExceptionFound = function(existingCombination) {
+    if (!existingCombination) {
+        return false;
+    }
+
+    // Exception for e.g. Google. They replace the username input with password input using identical className.
+    // If detected, remove the username from the combination.
+    if (existingCombination?.username?.className?.length > 0
```
Comment (varjolintu) [inline keepassxc-browser/common/sites.js:129]: This function was recently implemented with https://github.com/keepassxreboot/keepassxc-browser/pull/2861. It's possible that we need more than these two exceptions for combination handling with certain sites.

File: keepassxc-browser/content/form.js [hunk 3]
```diff
@@ -27,7 +27,7 @@ kpxcForm.activateCredentialBanner = async function(usernameValue, passwordInputs
         return;
     }
 
-    if (passwordField) {
+    if (passwordField && kpxcFields.isVisible(passwordField)) {
         await kpxc.setPasswordFilled(true);
```
Comment (varjolintu) [inline keepassxc-browser/content/form.js:31]: This call was triggered even if password field was not visible, preventing any password fills after that. Saw this on Epic Games site.

File: keepassxc-browser/content/icon-handler.js [hunk 4]
```diff
@@ -45,7 +45,13 @@ kpxcIcons.addIconsFromForm = async function(form) {
             // Special case where everything else has been hidden, but a single password field is now displayed.
             // For example PayPal and Amazon is handled like this.
             if (c.username && !c.password && c.passwordInputs.length === 1) {
-                kpxcIcons.addIcon(c.passwordInputs[0], kpxcIcons.iconTypes.DEFAULT);
+                // Use password input directly from form if found (Epicgames)
+                const passwordField = c.form?.querySelector('input[type=password]');
```
Comment (varjolintu) [inline keepassxc-browser/content/icon-handler.js:49]: Some sites (Epic Games) render the input field multiple times, breaking the actual reference to the visible input. This is not a pretty workaround, and I need to figure out if this should be the default behavior always with every site. The checks here are already getting messy.

File: keepassxc-browser/content/observer-helper.js [hunk 5]
```diff
@@ -247,8 +246,9 @@ kpxcObserverHelper.findInputsFromShadowDOM = function(target) {
 
 // Detects animations and transitions. Triggers handleObserverAdd() again on animationend/transitionend.
 kpxcObserverHelper.handleTransitions = function(target) {
-    const targetHasAnimations = target?.classList?.toString()?.includes('animate');
-    const targetHasDurations = target?.classList?.toString()?.includes('duration');
+    const classList = target?.classList?.toString();
+    const targetHasAnimations = classList?.includes('animate');
+    const targetHasDurations = classList?.includes('duration') || classList?.includes('transform');
```
Comment (varjolintu) [inline keepassxc-browser/content/observer-helper.js:251]: Transform events are also triggered with `transitionend`.

**Comment by droidmonkey** [comment]
Recommend fixing the code comments or punting this to the follow on release.

**Comment by varjolintu** [comment]
> Recommend fixing the code comments or punting this to the follow on release.

Those are just comments why I did some changes, for future reference :) Nothing to fix there.

**Review by droidmonkey — APPROVED** [review]
