### PR TITLE
Fix filling from popup

### LINKED ISSUE #1295: Fills wrong account information
## Expected Behavior

Going to a site for which I have many different saved credentials, I click the icon to see a dropdown of available credentials. I click the one I want and expect to see those creds filled into the user/pass fields. 

## Current Behavior

Instead, one of the other available credentials are entered into the user/pass fields. It's consistently wrong: if I click the 1st item in the list, I always get the 8th instead. If I click the 2nd, I always get the 7th, etc.

## Steps to Reproduce (for bugs)

1. 🤷‍♂️ 

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.7
Operating system: MacIntel
Browser: Mozilla Firefox 88.0

### PR DESCRIPTION
**Pull request by varjolintu**
After adding the sorting to the extension, filling from popup can fill a wrong username. Releasing a new version after the merge. I want to get this fixed asap.

Fixes #1295.

### CODE REVIEW

File: keepassxc-browser/content/keepassxc-browser.js [hunk 1]
```diff
@@ -941,7 +941,12 @@ kpxc.fillFromPopup = async function(id, uuid) {
     }
 
     await sendMessage('page_set_login_id', id);
-    kpxc.fillInCredentials(kpxc.combinations[0], kpxc.credentials[id].login, uuid);
+    const selectedCredentials = kpxc.credentials.find(c => c.uuid === uuid);
+    if (!selectedCredentials) {
+        return;
```
Comment (droidmonkey) [inline keepassxc-browser/content/keepassxc-browser.js:946]: Can we issue a console warning here? Does this warrant a user level warning as well?

Comment (varjolintu) [reply keepassxc-browser/content/keepassxc-browser.js:946]: A console warning should be enough.

**Review by droidmonkey — APPROVED** [review]
