### PR TITLE
Fix TOTP fill missing digits on some sites (fixes #2215)

### LINKED ISSUE #2215: TOTP in Authelia Login Mask is missing a digit with Autofill but works with Ctrl+T & pasting
## Steps to Reproduce
1. Set up an authelia instance & account
2. Set up TOTP 2FA for that account
3. Login with the Password for that account (works with KeePass Autofill)
4. Get to the TOTP Screen for that account and use the autofill feature

## Expected Behavior
the TOTP fill out the complete TOTP Token

## Actual Behavior
- the TOTP Code is filled out but is missing the last digit
- When I go to KeePass and Use Ctrl+T to get the token and paste it into the webpage, it works

## Context
I set up authelia on my own server, but this should hopefully not matter.

KeePassXC - Version 2.7.8
Revision: f6757d3

Qt 5.15.11
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.19045

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 3.1.1

### PR DESCRIPTION
**Pull request by ElementW**
Fixes Authelia and Epic Games OTP fill by addressing two underlying problems:

1. Incorrect DOM event ordering and data
- So far only empty key events were sent, which may confuse OTP input implementations that rely on the text from those events instead of input field value.
- The "beforeinput" event was missing altogether.
- Reorder the events to comply to the UIEvents spec (https://w3c.github.io/uievents/#keypress-event-order) and change field.value at the expected moment in that order.

2. Focus events were not sent
   As described in [#2215 (comment)](https://github.com/keepassxreboot/keepassxc-browser/issues/2215#issuecomment-3629070227), the extension focuses fields sequentially when filling in the OTP digits, but this does not trigger focus/blur events as this is performed within the same window event loop cycle, throwing off certain implementations of multi-textfield OTP input; in the case of Authelia filling an internal digit buffer starting from nonexistent index -1.

   Sending those events manually was attempted but did not yield satisfactory results as some frameworks like React use Promise objects to schedule their state update, merely resulting in the problem being pushed down the line.

   Instead, makes kpxcFill.setValueWithChange async so it can await on an empty Promise of its own, giving time for the user agent to trigger the appropriate focus events as well as for pages' scripts to settle.

## Screenshots or videos

[Authelia login flow](https://github.com/user-attachments/assets/9b9e7523-c283-4e05-8687-74f9f16c6257)

[Epic login flow](https://github.com/user-attachments/assets/858a4421-5ec6-4c95-b8a3-c79076dd49fd)

## Testing strategy
`npx playwright test` tests pass (bar the skipped URL matching ones)
Manually tested login flows on the following sites:

| Site | OTP style | Before PR | After PR |
| ---- | --------- | --------- | -------- |
| Authelia | Multi | ❌ | ✅ |
| [Epic](https://www.epicgames.com/) | Multi | ❌ | ✅ |
| [Printables](https://www.printables.com/) | Multi | ✅ | ✅ |
| [Paypal](https://www.paypal.com/) | Multi | ✅ | ✅ |
| [ebay](https://www.ebay.com/) | Multi | ✅ | ✅ |
| [itch.io](https://itch.io/) | Single | ✅ | ✅ |
| [atlas.ripe.net](https://atlas.ripe.net/) | Single | ✅ | ✅ |

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: keepassxc-browser/content/fill.js [hunk 1]
```diff
@@ -401,12 +401,23 @@ kpxcFill.setValueWithChange = function(field, value, forced = false) {
...
-    field.dispatchEvent(new KeyboardEvent('keydown', { bubbles: true, cancelable: false }));
-    field.dispatchEvent(new KeyboardEvent('keypress', { bubbles: true, cancelable: false }));
-    field.dispatchEvent(new KeyboardEvent('keyup', { bubbles: true, cancelable: false }));
+
+    // Use a delay to allow focus events to trigger and to give some
+    // breathing room to frameworks that rely on promises to update their
+    // state, like React. Not doing so can break OTP input, see issue #2215.
+    await Promise.resolve();
+
+    field.dispatchEvent(new FocusEvent('focus', { bubbles: false, calcelable: false }));
```
Comment (varjolintu) [inline keepassxc-browser/content/fill.js]: Typos here and below.

Comment (ElementW) [reply keepassxc-browser/content/fill.js]: Good catch, fixed

**Review by varjolintu — APPROVED** [review]
Thank you! :)
