### PR TITLE
Various fixes for 1.8.0 release

### LINKED ISSUE #1639: Issue saving form with Text Field, Username and Password
I've a website as follows:

image

- text field
- username
- password

When trying to save the form, I get this in the console:

```
keepassxc-browser.js:460 Uncaught (in promise) TypeError: combination[givenType].includes is not a function
    at kpxcFields.getCombination (keepassxc-browser.js:460:76)
    at kpxc.rememberCredentialsFromContextMenu (keepassxc-browser.js:1542:42)
    at keepassxc-browser.js:2105:18
```

The website is https://www.bbva.com.ar/ (argentinian bank)

## Expected Behavior
I should be able to save the form

## Current Behavior
Fails with error.

## Steps to Reproduce (for bugs)
1. Go to https://bbva.com.ar
2. fill random number, username and random password
3. right click, kepassxc-browser -> save form

## Debug info
KeePassXC -2.7.1
KeePassXC-Browser - 1.7.12
Operating system: Mac
Browser: Chrome

### PR DESCRIPTION
**Pull request by varjolintu**
Fixes few minor bugs found on first release test run:
- New upper row popup buttons are different height (Firefox)
- TOTP icon is gray in the second page even when credentials are filled (happened on Mastodon sites). Added a check for previously filled credential UUID. Also fixed UUID returning an integer when it should be string/undefined.
- Icon stayed gray if database was opened on one tab and switched to another tab that has credential. The icon states were updated too soon.

Fixes #1639.

### CODE REVIEW

File: keepassxc-browser/background/page.js [hunk 1]
```diff
@@ -321,10 +321,9 @@ page.retrieveCredentials = async function(tab, args = []) {
 
 page.getLoginId = async function(tab) {
     // If there's only one credential available and loginId is not set
-    if (page.tabs[tab.id] && page.tabs[tab.id].loginId < 0
-        && page.tabs[tab.id]
+    if (page.tabs[tab.id] && !page.tabs[tab.id].loginId
         && page.tabs[tab.id].credentials.length === 1) {
-        return 0; // Index to the first credential
+        return page.tabs[tab.id].credentials[0].uuid;
```
Comment (droidmonkey) [inline keepassxc-browser/background/page.js:326]: for clarity in reading you should store the tab in a variable: `currentTab = page.tabs[tab.id]`

File: keepassxc-browser/content/fields.js [hunk 2]
```diff
@@ -149,7 +149,8 @@ kpxcFields.getCombination = async function(field, givenType) {
         if (!givenType && Object.values(combination).find(c => c === field)) {
             return combination;
         } else if (givenType && combination[givenType]) {
-            if (combination[givenType] === field || combination[givenType].includes(field)) {
+            if (combination[givenType] === field
+                || (Array.isArray(combination[givenType]) && combination[givenType].includes(field))) {
                 return combination;
             }
         }
```
Comment (droidmonkey) [inline keepassxc-browser/content/fields.js:156]: This might be more readable like this:

```
if (givenType) {
    // strictly search a given type
	c = combination[givenType];
	if (c && (c === field || (Array.isArray(c) && c.includes(field)) {
		return combination;
	}
} else if (Object.values(combination).find(c => c === field)) {
	return combination;
}
```

**Review by droidmonkey — APPROVED** [review]

**Comment by varjolintu** [comment]
So far I haven't found new bugs in daily use after these fixes.

**Comment by varjolintu** [comment]
Merging this after #1390.

**Comment by droidmonkey** [comment]
Ready for me?

**Comment by varjolintu** [comment]
> Ready for me?

I want to merge this after the Custom Login Field changes. Easier that way if there's any conflicts.
