### PR TITLE
Fix autocomplete menu with keyboard

### LINKED ISSUE #1293: FireFox 87 can't use arrow-keys to select login
FireFox has just updated to v87, and an issue identical to the one below has started happening again.

https://github.com/keepassxreboot/keepassxc-browser/issues/1207

Symptoms are exactly the same, except, if I click in the login-box, then it shows credentials in a dropdown, and I can then select using the arrow keys after that.

### PR DESCRIPTION
**Pull request by varjolintu**
#1248 broke this partially. The Autocomplete menu cannot be opened from the keyboard. It only works if it has been opened at least once using a mouse. With multiple menus supported, the input field must always point to the target element.

Fixes #1293.

### CODE REVIEW

File: keepassxc-browser/content/autocomplete.js [hunk 1]
```diff
@@ -197,23 +198,23 @@ class Autocomplete {
...
         } else if (e.key === 'Tab') {
             // Return if value is not in the list
-            if (this.input.value !== '' && !this.elements.some(c => c.value === this.input.value)) {
+            if (inputField.value !== '' && !this.elements.some(c => c.value === inputField.value)) {
                 this.closeList();
                 return;
             }
 
-            this.index = this.elements.findIndex(c => c.value === this.input.value);
+            this.index = this.elements.findIndex(c => c.value === input.value);
```
Comment (droidmonkey) [inline keepassxc-browser/content/autocomplete.js:206]: Should this be `=== inputfield.value` ?

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: keepassxc-browser/content/autocomplete.js (hunk 1 above)
Comment (varjolintu) [reply keepassxc-browser/content/autocomplete.js:206]: Yes. Fixed.

**Review by droidmonkey — APPROVED** [review]
