### PR TITLE
Ignore password buttons on form submit button detection

### LINKED ISSUE #2880: Password is not saved OR the saved password is not what i typed
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

- Sometimes the extension does not offer to save credentials at all, and my entered username and password are lost.
- Other times it prompts to save, but the password stored in the vault is a 32-character random string (lowercase letters and digits) instead of the password I typed.

### Steps to Reproduce

1. went to [cryptomator](https://community.cryptomator.org/signup) or any of these discourse forums sites even [Tor](https://forum.torproject.org/signup) has one, while vault was open
2. typed email and user name
3. (NOT SAVING ANYTHING bug) manually pasted the password from pass generator, didn't click on "show password" eye icon. got signed into site but KeePassXC didn't saved anything, didn't even show any dialog to do so.
4. (SAVING WRONG PASSWORD bug) pasted the password from pass generator (or leave it empty, doesn't make a difference) DID click on "show password" eye icon
KeePassXC prompted to save credentials but it saved some 32-long string (number+small letters) 

### Expected Versus Actual Behavior

Expected behavior: same as KeePassXC on [Memrise](https://app.memrise.com) — enter username/email and password, submit, and then be prompted to save the new credentials on the next page. Currently the prompt is either not shown or captures the wrong field. Also, the KeePassXC dialog appears when I click the "show/hide password" button, which seems counterintuitive since that control is unrelated to saving credentials.

I'm migrating from Bitwarden to KeePassXC on Fedora 43 (GNOME) and am unsure whether this is intended behavior or a bug. Any guidance would be appreciated—thanks.

### KeePassXC Debug Information

```Text
KeePassXC - Version 2.7.11
Revision: 01e5b6e
Distribution: Flatpak

Qt 5.15.18
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.18.10-200.fc43.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.7.1
```

### Operating System

Linux

### Linux Desktop Environment

Gnome

### Linux Windowing System

Wayland

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX". )
When detecting submit buttons from form, ignore any buttons thas includes `password` in the `classList` or `id`. This prevents triggering the Credential Banner when it's not actually needed.

* Fixes #2880

## Screenshots or videos
[NOTE]: # ( Use if available. )
[NOTE]: # ( Do not include screenshots of your actual database credentials! )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( Also describe how to test the changes manually. )
Manually using https://community.cryptomator.org/signup page.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

File: keepassxc-browser/content/form.js [hunk 1]
```diff
@@ -66,6 +66,8 @@ kpxcForm.getFormSubmitButton = function(form) {
         return;
     }
 
+    const hasPasswordClassOrId = (button) => button
+        && (button?.classList.value?.includes('password') || button?.id?.includes('password'));
```
Comment (droidmonkey) [inline keepassxc-browser/content/form.js]: perhaps we should do this as case insensitive check

**Review by droidmonkey — APPROVED** [review]
