### PR TITLE
Switch from index to uuid

### LINKED ISSUE #1302: Fill TOTP pulling from wrong account when 2 exist in different groups in KeePassXC database (tested with ProtonMail)
[Edited due to additional information being found [here](https://github.com/keepassxreboot/keepassxc-browser/issues/1302#issuecomment-817181649)]

## Expected Behavior

The OTP code that is generated when when using the browser extension is accepted, and for the correct account.

## Current Behavior

When the OTP code is generated via the KeePassXC-browser extension, it is denied. Additional investigation determined that it is being pulled from the wrong account.

## Steps to Reproduce (for bugs)

1. Have 2 ProtonMail accounts (with 2FA enabled) in the same folder in KeePassXC.
2. Login to ProtonMail with one account.
3. On OTP page, witness OTP dropdown stating the other ProtonMail account

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8
Operating system: Windows 10
Browser: Firefox 87, Vivaldi Snapshot 3.8.2254.3

### LINKED ISSUE #1303: No TOTP found for entry but clicking another entry gives correct TOTP
## Expected Behavior

When I select an entry from the plugin icon in the top right I expect that entry to be pasted. Same goes for TOTP pasting. Watch the attached video.

## Current Behavior

When I select an entry from the plugin icon in the top right it gives me another one. See video.

## Steps to Reproduce (for bugs)

1. I connected two databases
2. I went in on GitHub
3. Three entries popped up and I clicked on the plugin icon in the top right and selected the one I wanted
4. The wrong credentials got pasted in the login form

### Demo

In the end the TOTP code that got pasted worked, even though the browser plugin claimed it was for another entry.

https://user-images.githubusercontent.com/1107419/114268280-970fba80-9a00-11eb-8cb2-ee363cb4e51b.mp4

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.7
Operating system: macOS Catalina 10.15.7
Browser: Firefox 87.0

I have two databases connected with two different unique identifiers.

### PR DESCRIPTION
**Pull request by varjolintu**
Switch from index to uuid when filling credentials/TOTP from previous page. With the new sorting system just an index is not a reliable way to handle data.

Fixes #1302.
Fixes #1303.

### CODE REVIEW

File: keepassxc-browser/content/keepassxc-browser.js [hunk 1]
```diff
@@ -1508,9 +1508,12 @@ kpxc.rememberCredentials = async function(usernameValue, passwordValue, urlValue
         if (credentialsList.length === 1) {
             usernameValue = credentialsList[0].login;
         } else if (credentialsList.length > 1) {
-            const index = await sendMessage('page_get_login_id');
-            if (index >= 0) {
-                usernameValue = credentialsList[index].login;
+            const uuid = await sendMessage('page_get_login_id');
```
Comment (droidmonkey) [inline keepassxc-browser/content/keepassxc-browser.js:1511]: Sometimes we send `''` sometimes we leave the second parameter empty. Let's be consistent on that one.

**Review by droidmonkey — CHANGES_REQUESTED** [review]

File: keepassxc-browser/content/keepassxc-browser.js (hunk 1 above)
Comment (varjolintu) [reply keepassxc-browser/content/keepassxc-browser.js:1511]: Are you mixing up `get` and `set`?

Comment (droidmonkey) [reply keepassxc-browser/content/keepassxc-browser.js:1511]: Oof I totally am, that functionality is an innocent typo away!

**Review by droidmonkey — APPROVED** [review]
