### PR TITLE
Inject passkeys scripts at document_start

### LINKED ISSUE #2431: Trouble using passkeys on Ping Authenticate
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

Hi,

I'm trying to use KeepassXC to authenticate on company portal that uses PingID auth (https://www.pingidentity.com/en.html)
I was able to enroll KeepassXC as 'biometrics' authentcation.

But authentication step doesn't work. Sometimes no message from KeepassXC (I think because authentication happens immediately during page load and browser extension is not able to inject code). But when request is captured, keepassxc shows "no logins found"

```
{
  "challenge": "EDITED1",
  "enterpriseAttestationPossible": false,
  "rpId": "pingone.eu",
  "timeout": 120000,
  "userVerification": "required",
  "allowCredentials": [
    {
      "id": "EDITED2",
      "transports": [
        "internal"
      ],
      "type": "public-key"
    }
  ]
}
```
I've tried to debug it. And found that KeepassXC compare 'allowCredentials' with `credentialId` field of passkey. But for my case it's not same as `EDITED2`. I think it's because of `type=public-key`. So to match it properly it's required to get public part from private key..

Note: even skipping this check for now (so that entry is actually used) for some reason it don't accept response. Not sure why. PingID reloads page before trying to authenticate and before showing error message, so it's hard to capture something.

### Steps to Reproduce

Hard to reproduce because it's not public service

### Expected Versus Actual Behavior

_No response_

### KeePassXC Debug Information

```Text
KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: fb022cb

Qt 5.15.15
Debugging mode is enabled.

Operating system: Debian GNU/Linux trixie/sid
CPU architecture: x86_64
Kernel: linux 6.11.9-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys

Cryptographic libraries:
- Botan 3.6.1
```

### Operating System

Linux

### Linux Desktop Environment

KDE

### Linux Windowing System

X11

### LINKED ISSUE #2434: Injected passkeys.js is leaking its variables and functions to the site
Its injected here:
https://github.com/keepassxreboot/keepassxc-browser/blob/60355e8e1c8e8a3deecfb2f61a0649802951bc18/keepassxc-browser/content/keepassxc-browser.js#L872-L874

As a result, all of its variables are just readable by the site, easy enough to confirm with console:
Image

### PR DESCRIPTION
**Pull request by varjolintu**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX". )
Loads passkey injection script at document start. It gives a higher probability to catch WebAuthn requests made by the browser. There are several sites that do this before the document loading is finished.

Also wraps the content of `passkeys.js` inside async so the variables and functions will no leak to the site.

Fixes #2431.
Fixes #2434.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( Also describe how to test the changes manually. )
Manually. If Chromium based browser is used, the `manifest_chromium.json` must be copied manually over the default `manifest.json`.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Refactor (significant modification to existing code)

### CODE REVIEW

**Comment by dionorgua** [comment]
@varjolintu please let me know you need more testing from my side with Ping ID

**Comment by droidmonkey** [comment]
Will give this branch a solid test today

File: keepassxc-browser/content/passkeys-utils.js [hunk 1]
```diff
@@ -46,8 +46,8 @@ const kpxcPasskeysUtils = {};
 // Sends response from KeePassXC back to the injected script
 kpxcPasskeysUtils.sendPasskeysResponse = function(publicKey, errorCode, errorMessage) {
     const response = errorCode
-        ? { errorCode: errorCode, errorMessage: errorMessage, fallback: kpxc.settings.passkeysFallback }
-        : { publicKey: publicKey, fallback: kpxc.settings.passkeysFallback };
+        ? { errorCode: errorCode, errorMessage: errorMessage, fallback: kpxcPasskeysUtils?.passkeysFallback }
+        : { publicKey: publicKey, fallback: kpxcPasskeysUtils?.passkeysFallback };
     const details = isFirefox() ? cloneInto(response, document.defaultView) : response;
```
Comment (a2kolbasov) [inline keepassxc-browser/content/passkeys-utils.js:51]: `ReferenceError: isFirefox is not defined`

`isFirefox` is declared in keepassxc-browser/common/global.js and is run at `document_idle` (as in manifest)

**Comment by a2kolbasov** [comment]
Manually tested in Firefox. On sites

- https://gitlab.com/
- https://accounts.zoho.eu/

the error is fixed, the passkey request occurs on the first try.

On https://app.simplelogin.io/ the script still doesn't have time to override properties before a request.

<details><summary>(location of <code>console.debug</code>)</summary>

```diff
diff --git a/keepassxc-browser/content/passkeys.js b/keepassxc-browser/content/passkeys.js
index 4ca7e9c..3da1638 100644
--- a/keepassxc-browser/content/passkeys.js
+++ b/keepassxc-browser/content/passkeys.js
@@ -207,6 +207,7 @@
         Object.defineProperty(window.PublicKeyCredential, 'isUserVerifyingPlatformAuthenticatorAvailable', {
             value: isUserVerifyingPlatformAuthenticatorAvailable,
         });
+        console.debug('[*] kpxc-passkeys loaded');
     } catch (err) {
         console.log('Cannot override navigator.credentials: ', err);
     }
```

</details>

app.simplelogin.io console

**Comment by a2kolbasov** [comment]
Manually tested in Firefox. On sites

- https://gitlab.com/
- https://accounts.zoho.eu/

the error is fixed, a passkey request occurs on the first try.

On https://app.simplelogin.io/ the script still doesn't have time to override properties before a request.

<details><summary>(location of <code>console.debug</code>)</summary>

```diff
diff --git a/keepassxc-browser/content/passkeys.js b/keepassxc-browser/content/passkeys.js
index 4ca7e9c..3da1638 100644
--- a/keepassxc-browser/content/passkeys.js
+++ b/keepassxc-browser/content/passkeys.js
@@ -207,6 +207,7 @@
         Object.defineProperty(window.PublicKeyCredential, 'isUserVerifyingPlatformAuthenticatorAvailable', {
             value: isUserVerifyingPlatformAuthenticatorAvailable,
         });
+        console.debug('[*] kpxc-passkeys loaded');
     } catch (err) {
         console.log('Cannot override navigator.credentials: ', err);
     }
```

</details>

app.simplelogin.io console

**Comment by varjolintu** [comment]
@a2kolbasov I think SimpleLogin only supports security keys for now, and that can sometimes be more problematic, and the OS/browser level gets ahead of any scripts.

**Comment by dionorgua** [comment]
Ping ID works with current version of branch. 10/10 using firefox.

**Review by droidmonkey — APPROVED** [review]
